### ISSUE TITLE
Font not working on site

### ISSUE THREAD

**Issue by wusgitaccount** [wusgitaccount/magazine#1]
Font 'Coda' works in file but not when pushed onto site. Comes up with error message: Mixed Content: The page at 'https://wusgitaccount.github.io/magazine/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Coda:800'. This request has been blocked; the content must be served over HTTPS.

**Comment by ellysmlly** [comment]
Cool thanks for writing out the info & errors - was very helpful to clearly figure out the problem

Your error is telling you that your font must be served over HTTPS 

Currently the link your using is **HTTP**
`http://fonts.googleapis.com/css?family=Coda:800`

You need to update it to use **HTTPS** for the font to come through
`https://fonts.googleapis.com/css?family=Coda:800`

Give that a go and let me know if the font works for you 

@sehsarah might be able to explain the difference between these two link paths tomorrow in class

**Comment by wusgitaccount** [comment]
I've changed it the HTTPS, but it's not allowing me to push it onto my site as there is this '...' file that is locked for editing. Not sure why it's there.

**Comment by sehsarah** [comment]
Sounds like you have a merge conflict or something like that, find me in class on Tuesday and I can have a look 👍

**Comment by wusgitaccount** [comment]
It's all good, I can manually select the files I want to add so the font is working now, just can't delete that ... file.
